language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_deploy:
  - cargo doc --no-deps

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: target/doc/
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    type: push
    branch: master
    condition: $TRAVIS_RUST_VERSION = stable
