[package]
name = "piecewise-linear"
version = "0.1.0"
authors = ["Matthieu Felix <matthieufelix@gmail.com>"]
edition = "2018"

[dependencies]
geo = "0.12.2"
num-traits = "0.2.8"
serde = { version = "1.0", optional = true, features = ["derive"] }

[features]
default = []
use-serde = ["serde"]
